### ISSUE TITLE
 No module named 'inference_img'

### ISSUE THREAD

**Issue by NenelFX** [may-son/RIFE-dropfix-and-convert#1]
convert_fps.py -h
Traceback (most recent call last):
  File "convert_fps.py", line 12, in <module>
    from inference_img import LoadModel, StartModel, RatioSplit, ReadImage, WriteImage
ModuleNotFoundError: No module named 'inference_img'

**Comment by may-son** [comment]
You need to have all python files and at least one RIFE model. You can't just download one file and expect it to work.
